### ISSUE TITLE
Default nginx.htpasswd admin password misleading?

### ISSUE THREAD

**Issue by infinite-dao** [aborroy/acs-proxy#3]
Hej hej,

what password is the default `nginx.htpasswd` providing? 

Because I found it may be misleading to use  `YWG41BPzVAkN6` from [`nginx.htpasswd`](https://github.com/aborroy/acs-proxy/blob/6ace091e62e890a1fac3ec18b47da050eee7565b/config/nginx.htpasswd#L1)

After I missed to log in (mentioned in https://github.com/Alfresco/alfresco-docker-installer/issues/74#issuecomment-824016332) with password `admin` e.g. to my custom site `https://custom-server-name.org/solr` and other passwords that I tried, I found it has to be generated by `htpasswd` (see [Restricting Access with HTTP Basic Authentication; docs.nginx.com](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/)):

    htpasswd /path/to/nginx.htpasswd whateverusername

So if the default password shall be `YWG41BPzVAkN6`, then `nginx.htpasswd` should contain e.g:

    admin:$apr1$Nqdhv8hR$gEsnbvQXzZKM6stsIoYFz1

… or if the password shall be `admin` then e.g:

    admin:$apr1$94LKbA3l$fawCs80fVfXNG.IMlazEl1

Right? After grasping and setting it, I could log in as expected to `https://custom-server-name.org/solr` web console ;-)

**Comment by aborroy** [comment]
It was `admin`, you are hashing again the hashed password.
